repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
        exclude: ^2022/inputs/day05
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.13.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--target-version, py310]
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.3.0
    hooks:
      - id: flakeheaven
        additional_dependencies:
          - flake8-annotations-complexity
          - flake8-bandit
          - flake8-builtins
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-noqa
          - pep8-naming
