repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        types: [python]
      - id: check-toml
        types: [toml]
      - id: check-yaml
        types: [yaml]
      - id: end-of-file-fixer
        types: [python]
      - id: check-merge-conflict
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        types: [python]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      types: [python]
