###############################################################################
# flake8 / flakeheaven
###############################################################################
[tool.flakeheaven]
max_complexity = 10
format = "grouped"
baseline = "baseline.txt"

# Base rules
#############################
[tool.flakeheaven.plugins]
"*" = [
    "+*",
    "-E501", # long lines
    "-E203", # conflict with black on PEP8 interpretation
    "-W503",  # deprecated rule: https://www.flake8rules.com/rules/W503.html
]
flake8-builtins = [
    "+*",
    "-A003", # class attribute is shadowing a python builtin
]
flake8-bandit = [
    "+*",
    "-S101", # Use of assert detected.
]
